language: python
python:
  - "3.8"
git:
    # Handle git submodules yourself
    submodules: false
before_install:
  - mv homeassistant/mock_secrets.yaml homeassistant/secrets.yaml
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
addons:
  apt:
    packages:
    - libudev-dev
install:
  - pip3 install homeassistant==0.113.3
script:
  - hass --script check_config --config homeassistant
