language: python
python:
  - "3.5"
git:
    # Handle git submodules yourself
    submodules: false
before_install:
  - cd homeassistant
  - mv mock_secrets.yaml secrets.yaml
  # Use sed to replace the SSH URL with the public URL, then initialize submodules
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
