homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  # Customization file
  customize: #!include customize.yaml
    sensor.house_entry_exit_recent_data_ready:
      body: '<ommitted>'

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

discovery:
    
# Show the introduction message on startup.
# introduction:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Sensors
sensor:
  # Weather prediction
  - platform: yr
  
  # Gmail - FrontPoint door sensor
  - platform: imap_email_content
    server: imap.gmail.com
    port: 993
    username: !secret gmail_username
    password: !secret gmail_password
    senders:
      - donotreply@frontpointsecurity.com
    name: house_entry_exit_recent_data_ready
    value_template: >-
      {% if 'was Opened at' in subject %}
        {# works? {% set mydict = {'triggered':true, 'last_date':date} %} #}
        {# this does not work: {% set mydict['triggered'] = true %} #}
        {# also works? {{ mydict }} #}
        available
      {% endif %}
      
  - platform: template
    sensors:
      house_entry_exit_recent_triggered:
        value_template: >-
          {% if is_state('sensor.house_entry_exit_recent_data_ready', 'available') %}
            {{ state_attr('sensor.house_entry_exit_recent_data_ready', 'date') }}
          {% else %}
            false: {{ states('sensor.house_entry_exit_recent_data_ready') }}
          {% endif %}

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://hassio.local:3218
    
#alarm_control_panel:
#  platform: alarmdotcom
#  username: !secret frontpoint_username
#  password: !secret frontpoint_password
#  name: FrontPoint

media_player:
  - platform: plex
    entity_namespace: 'plex'
    include_non_clients: true
    scan_interval: 5
    show_all_controls: false
    use_custom_entity_ids: true
    use_episode_art: true
    remove_unavailable_clients: false
    client_remove_interval: 600
