
- alias: 'Set night light mode'
  trigger:
    - platform: time
      at: '21:30'
  action:
    - service: light.turn_on
      entity_id: group.upstairs_bathroom_lights
      data:
        brightness: 1
    - delay: '00:00:10'
    - service: light.turn_off
      entity_id: group.upstairs_bathroom_lights


- alias: 'Set day light mode'
  trigger:
    - platform: time
      at: '4:30'
  action:
    - service: light.turn_on
      entity_id: group.upstairs_bathroom_lights
      data:
        brightness: 80
    - delay: '00:00:10'
    - service: light.turn_off
      entity_id: group.upstairs_bathroom_lights
