
# Samsung button events:
#  - 1001: Long press
#  - 1002: Single press
#  - 1004: Double press


- alias: 'Upstairs hallway motion triggered (day)'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_eco_upstairs_hallway
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: time
      after: '05:00'
      before: '21:00'
  action:
    - service: timer.cancel
      entity_id: timer.upstairs_hallway_lights
    - service: light.turn_on
      entity_id: group.upstairs_hallway
      data:
        brightness_pct: 100


- alias: 'Upstairs hallway motion triggered (night)'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_eco_upstairs_hallway
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
    - condition: time
      after: '21:00'
      before: '05:00'
  action:
    - service: timer.cancel
      entity_id: timer.upstairs_hallway_lights
    - service: light.turn_on
      entity_id: group.upstairs_hallway
      data:
        brightness: 1


- alias: 'Upstairs hallway motion cleared'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_eco_upstairs_hallway
    from: "on"
    to: "off"
  action:
    - service: timer.start
      entity_id: timer.upstairs_hallway_lights


- alias: 'Upstairs hallway lights timeout'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.upstairs_hallway_lights
  action:
      service: light.turn_off
      entity_id: group.upstairs_hallway


- alias: 'Kitchen lights toggle'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: button_st_kitchen
        event: 1002 # Single press
  action:
    - service: light.toggle
      entity_id: group.kitchen


- alias: 'Office lights toggle'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: button_st_office
        event: 1002 # Single press
  action:
    - service: light.toggle
      entity_id: group.office


- alias: 'Master bedroom lights toggle'
  trigger:
    - platform: event
      event_type: deconz_event
      event_data:
        id: button_st_master_bedroom
        event: 1002 # Single press
  action:
    - service: light.toggle
      entity_id: group.master_bedroom


- alias: 'Set night light mode'
  trigger:
    - platform: time
      at: '21:30'
  action:
    - service: light.turn_on
      entity_id: group.upstairs_bathroom_lights
      data:
        brightness: 1
    - delay: '00:00:02'
    - service: light.turn_off
      entity_id: group.upstairs_bathroom_lights


- alias: 'Set day light mode'
  trigger:
    - platform: time
      at: '4:30'
  action:
    - service: light.turn_on
      entity_id: group.upstairs_bathroom_lights
      data:
        brightness_pct: 80
    - delay: '00:00:02'
    - service: light.turn_off
      entity_id: group.upstairs_bathroom_lights


- alias: 'Enable evening'
  trigger:
    - platform: time
      at: '16:00'
  action:
  #   - service: switch.turn_on
  #     entity_id: switch.christmas_tree


- alias: 'Enable night'
  trigger:
    - platform: time
      at: '23:00'
  action:
    - service: switch.turn_off
      entity_id: switch.christmas_tree


- alias: 'Entry lights'
  trigger:
    - platform: state
      entity_id: binary_sensor.multi_sensor_st_front_door_openclose
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: timer.start
      entity_id: timer.entry_lights
    - service: light.turn_on
      entity_id: group.outside_lights


- alias: 'Entry lights timeout'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.entry_lights
  action:
    - service: light.turn_off
      entity_id: light.outside_front
    - condition: state
      entity_id: timer.outside_kitchen_lights
      state: 'idle'
    - service: light.turn_off
      entity_id: light.outside_kitchen


- alias: 'Outside kitchen lights'
  trigger:
    - platform: state
      entity_id: binary_sensor.multi_sensor_st_kitchen_door_openclose
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: timer.start
      entity_id: timer.outside_kitchen_lights
    - service: light.turn_on
      entity_id: light.outside_kitchen


- alias: 'Outside kitchen lights timeout'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.outside_kitchen_lights
  action:
    - condition: state
      entity_id: timer.entry_lights
      state: 'idle'
    - service: light.turn_off
      entity_id: light.outside_kitchen


- alias: 'Foyer motion lights'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_hue_foyer
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: sun.sun
      state: 'below_horizon'
  action:
    - service: timer.start
      entity_id: timer.foyer_lights
    - service: light.turn_on
      entity_id: light.foyer
      data:
        brightness_pct: 100


- alias: 'Foyer lights timeout'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.foyer_lights
  action:
      service: light.turn_off
      entity_id: light.foyer
