homeassistant:

  # Name of the location where Home Assistant is running
  name: Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0

  # metric for Metric, imperial for Imperial
  unit_system: imperial

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York


##### --------------- All others are listed alphabetically --------------- #####

alexa:
  smart_home:
    filter:
      exclude_entities:
        # Exclude any possible hue group dupes from HA group overrides
        - light.downstairs_hallway_2
        - light.foyer_2
        - light.guest_bedroom_2
        - light.house_2
        - light.kitchen_2
        - light.laundry_room_2
        - light.living_room_2
        - light.master_bedroom_2
        - light.office_2
        - light.outside_2
        - light.upstairs_bathroom_2
        - light.upstairs_hallway_2

        # Group dupes created just for lovelace
        - group.dining_room
        - group.downstairs_hallway
        - group.guest_bedroom
        - group.kitchen
        - group.laundry_room
        - group.living_room
        - group.master_bedroom
        - group.office
        - group.outside
        - group.upstairs_bathroom
        - group.upstairs_hallway

        # Exclude all the other Alexa items
        - media_player.alexa_apps_jc
        - media_player.alexa_dining_room
        - media_player.alexa_everywhere
        - media_Player.alexa_kitchen
        - media_player.alexa_living_room
        - media_player.alexa_master_bedroom
        - media_Player.alexa_music_room
        - media_player.alexa_note_10_jc
        - media_Player.alexa_office
        - media_Player.alexa_upstairs_bathroom
        - sensor.alexa_dining_room_next_alarm
        - sensor.alexa_dining_room_next_reminder
        - sensor.alexa_dining_room_next_timer
        - sensor.alexa_kitchen_next_alarm
        - sensor.alexa_kitchen_next_reminder
        - sensor.alexa_kitchen_next_timer
        - sensor.alexa_living_room_next_alarm
        - sensor.alexa_living_room_next_reminder
        - sensor.alexa_living_room_next_timer
        - sensor.alexa_master_bedroom_next_alarm
        - sensor.alexa_master_bedroom_next_reminder
        - sensor.alexa_master_bedroom_next_timer
        - sensor.alexa_music_room_next_alarm
        - sensor.alexa_music_room_next_reminder
        - sensor.alexa_music_room_next_timer
        - sensor.alexa_note_10_jc_next_alarm
        - sensor.alexa_note_10_jc_next_reminder
        - sensor.alexa_note_10_jc_next_timer
        - sensor.alexa_office_next_alarm
        - sensor.alexa_office_next_reminder
        - sensor.alexa_office_next_timer
        - sensor.alexa_upstairs_bathroom_next_alarm
        - sensor.alexa_upstairs_bathroom_next_reminder
        - sensor.alexa_upstairs_bathroom_next_timer
        - switch.alexa_apps_jc_dnd
        - switch.alexa_dining_room_dnd
        - switch.alexa_dining_room_repeat
        - switch.alexa_dining_room_shuffle
        - switch.alexa_everywhere_dnd
        - switch.alexa_everywhere_repeat
        - switch.alexa_everywhere_shuffle
        - switch.alexa_kitchen_dnd
        - switch.alexa_kitchen_repeat
        - switch.alexa_kitchen_shuffle
        - switch.alexa_living_room_dnd
        - switch.alexa_living_room_repeat
        - switch.alexa_living_room_shuffle
        - switch.alexa_master_bedroom_dnd
        - switch.alexa_master_bedroom_repeat
        - switch.alexa_master_bedroom_shuffle
        - switch.alexa_music_room_dnd
        - switch.alexa_music_room_repeat
        - switch.alexa_music_room_shuffle
        - switch.alexa_note_10_jc_dnd
        - switch.alexa_office_dnd
        - switch.alexa_office_repeat
        - switch.alexa_office_shuffle
        - switch.alexa_upstairs_bathroom_dnd
        - switch.alexa_upstairs_bathroom_repeat
        - switch.alexa_upstairs_bathroom_shuffle

api:

automation: !include automations.yaml
# Absolutely freaking required, even if empty -- otherwise refused on 8123
config:
conversation:

discovery:
  ignore:
  enable:
    # - philips_hue # Only needed for initial discovery

frontend:
  themes: !include_dir_merge_named themes


history:
http:

group: !include groups.yaml


influxdb:
  host: 192.168.1.56
  port: 8086
  username: !secret influxdb_username
  password: !secret influxdb_password
  database: homeassistant
  default_measurement: state
  ssl: true
  verify_ssl: false
# exclude stuff that is pointless to log
  # exclude:
  #   domains:
  #     - group
  #   entities:
  #     - sensor.other_junk_you_dont_care_about


input_boolean:
  # Icons from https://materialdesignicons.com/
  car_alarm_triggered:
    name: Car Alarm Triggered
    icon: mdi:shield-car
  house_alarm_triggered:
    name: House Alarm Triggered
    icon: mdi:shield-home
  single_occupant:
    name: Single occupant mode
    icon: mdi:account-check
  pending_mercedes_start:
    name: Flag Mercedes to start
    initial: false
    icon: mdi:car-cog
  pending_relinquish_to_motion:
    name: Flag relinquish to motion
    initial: false
    icon: mdi:motion-sensor
  pending_power_select_tvpc_office_ir:
    name: "Flag power on and select source for TV+PC Office Inside/Right"
    initial: false
    icon: mdi:arrow-expand-right
  pending_power_select_tvpc_office_ol:
    name: "Flag power on and select source for TV+PC Office Outside/Left"
    initial: false
    icon: mdi:arrow-expand-left
  pending_workout_finish:
    name: Flag workout finish
    initial: false
    icon: mdi:music-rest-whole
  pending_yamaha_skip_next:
    name: Flag skip next on yamaha
    initial: false
    icon: mdi:skip-next
  request_alexa_wheres_the_beer:
    name: Request where's the beer from Alexa
    initial: false
    icon: mdi:glass-mug-variant
  spotlight_mode:
    name: Spotlight mode (single occ)
    icon: mdi:spotlight


input_select:
  alarm_alert:
    name: Alarm Alert Status
    options:
      - Cleared
      - Alert active
      - Acknowledged
    icon: mdi:shield


input_text:
  alexa_actionable_notification:
    name: Alexa Actionable Notification Holder
    max: 255
    initial: '{"text":
        "This is a test of the alexa actions custom skill. Did it work?",
        "event": "actionable.skill.test"}'


light: !include lights.yaml

logbook:


logger:
  default: warning
  # logs:
    # homeassistant.components.alexa: debug
    #homeassistant.components.python_script: debug

media_player:
  - platform: androidtv
    name: Living Room NVIDIA Shield
    host: 192.168.1.63
    apps:
      tv.mrmc.mrmc: "Mr MC"

  - platform: androidtv
    name: Office OL Toshiba Fire TV
    device_class: firetv
    host: 192.168.1.73

  - platform: yamaha
    host: 192.168.1.64
    source_ignore:
      - "AUDIO1"
      - "AUDIO2"
      - "AV1"
      - "AV2"
      - "AV3"
      - "AV4"
      - "AV5"
      - "AV6"
      - "Deezer"
      - "HDMI3"
      - "HDMI4"
      - "HDMI5"
      - "SiriusXM"
      - "USB"
      - "V-AUX"
    source_names:
      HDMI1: "Nvidia Shield"
      HDMI2: "Xbox 360"
      PHONO: "Turntable / Vinyl"

mobile_app:
python_script:
recorder:


rest_command:
  autoremote_mercedes_start:
    url: !secret autoremote_msg_mercedes_start


script: !include_dir_merge_named scripts

sensor: !include sensors.yaml


switch:
  - platform: wake_on_lan
    mac: 8c:dc:d4:29:71:74
    host: 192.168.1.79
    name: Office IR TVPC
    turn_off:
      service: mqtt.publish
      data:
        topic: "iotlink/workgroup/tvpc-office-ir/commands/suspend"

  - platform: wake_on_lan
    mac: 64:51:06:5e:c7:e6
    host: 192.168.1.75
    name: Office OL TVPC
    turn_off:
      service: mqtt.publish
      data:
        topic: "iotlink/workgroup/tvpc-office-ol/commands/suspend"


system_health:
sun:
updater:
variable:
wake_on_lan:

zwave:
  usb_path: /dev/zwave0
