homeassistant:

  # Name of the location where Home Assistant is running
  name: Home

  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0

  # metric for Metric, imperial for Imperial
  unit_system: imperial

  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York


##### --------------- All others are listed alphabetically --------------- #####

alexa:
  smart_home:
    filter:
      exclude_entities:
        # Exclude any possible hue group dupes from HA group overrides
        - light.downstairs_hallway_2
        - light.foyer_2
        - light.guest_bedroom_2
        - light.house_2
        - light.kitchen_2
        - light.laundry_room_2
        - light.living_room_2
        - light.master_bedroom_2
        - light.office_2
        - light.outside_2
        - light.upstairs_bathroom_2
        - light.upstairs_hallway_2

        # Group dupes created just for lovelace
        - group.dining_room
        - group.downstairs_hallway
        - group.guest_bedroom
        - group.kitchen
        - group.laundry_room
        - group.living_room
        - group.master_bedroom
        - group.office
        - group.outside
        - group.upstairs_bathroom
        - group.upstairs_hallway

        # Exclude all the other Alexa items
        - media_player.alexa_apps_jc
        - media_player.alexa_dining_room
        - media_Player.alexa_downstairs_bathroom
        - media_player.alexa_everywhere
        - media_Player.alexa_kitchen
        - media_Player.alexa_laundry_room
        - media_player.alexa_living_room
        - media_player.alexa_master_bedroom
        - media_Player.alexa_music_room
        - media_player.alexa_note_10_jc
        - media_Player.alexa_office
        - media_Player.alexa_upstairs_bathroom
        - sensor.alexa_dining_room_next_alarm
        - sensor.alexa_dining_room_next_reminder
        - sensor.alexa_dining_room_next_timer
        - sensor.alexa_downstairs_bathroom_next_alarm
        - sensor.alexa_downstairs_bathroom_next_reminder
        - sensor.alexa_downstairs_bathroom_next_timer
        - sensor.alexa_kitchen_next_alarm
        - sensor.alexa_kitchen_next_reminder
        - sensor.alexa_kitchen_next_timer
        - sensor.alexa_laundry_room_next_alarm
        - sensor.alexa_laundry_room_next_reminder
        - sensor.alexa_laundry_room_next_timer
        - sensor.alexa_living_room_next_alarm
        - sensor.alexa_living_room_next_reminder
        - sensor.alexa_living_room_next_timer
        - sensor.alexa_master_bedroom_next_alarm
        - sensor.alexa_master_bedroom_next_reminder
        - sensor.alexa_master_bedroom_next_timer
        - sensor.alexa_music_room_next_alarm
        - sensor.alexa_music_room_next_reminder
        - sensor.alexa_music_room_next_timer
        - sensor.alexa_note_10_jc_next_alarm
        - sensor.alexa_note_10_jc_next_reminder
        - sensor.alexa_note_10_jc_next_timer
        - sensor.alexa_office_next_alarm
        - sensor.alexa_office_next_reminder
        - sensor.alexa_office_next_timer
        - sensor.alexa_upstairs_bathroom_next_alarm
        - sensor.alexa_upstairs_bathroom_next_reminder
        - sensor.alexa_upstairs_bathroom_next_timer
        - switch.alexa_apps_jc_dnd
        - switch.alexa_dining_room_dnd
        - switch.alexa_dining_room_repeat
        - switch.alexa_dining_room_shuffle
        - switch.alexa_downstairs_bathroom_dnd
        - switch.alexa_downstairs_bathroom_repeat
        - switch.alexa_downstairs_bathroom_shuffle
        - switch.alexa_everywhere_dnd
        - switch.alexa_everywhere_repeat
        - switch.alexa_everywhere_shuffle
        - switch.alexa_kitchen_dnd
        - switch.alexa_kitchen_repeat
        - switch.alexa_kitchen_shuffle
        - switch.alexa_laundry_room_dnd
        - switch.alexa_laundry_room_repeat
        - switch.alexa_laundry_room_shuffle
        - switch.alexa_living_room_dnd
        - switch.alexa_living_room_repeat
        - switch.alexa_living_room_shuffle
        - switch.alexa_master_bedroom_dnd
        - switch.alexa_master_bedroom_repeat
        - switch.alexa_master_bedroom_shuffle
        - switch.alexa_music_room_dnd
        - switch.alexa_music_room_repeat
        - switch.alexa_music_room_shuffle
        - switch.alexa_note_10_jc_dnd
        - switch.alexa_office_dnd
        - switch.alexa_office_repeat
        - switch.alexa_office_shuffle
        - switch.alexa_upstairs_bathroom_dnd
        - switch.alexa_upstairs_bathroom_repeat
        - switch.alexa_upstairs_bathroom_shuffle

api:

automation: !include automations.yaml

# Absolutely freaking required, even if empty -- otherwise refused on 8123
config:
conversation:

discovery:
  ignore:
  enable:
    # - philips_hue # Only needed for initial discovery

frontend:
  themes: !include_dir_merge_named themes


history:
http:

group: !include groups.yaml


influxdb:
  host: 192.168.1.56
  port: 8086
  username: !secret influxdb_username
  password: !secret influxdb_password
  database: homeassistant
  default_measurement: state
  ssl: true
  verify_ssl: false
# exclude stuff that is pointless to log
  # exclude:
  #   domains:
  #     - group
  #   entities:
  #     - sensor.other_junk_you_dont_care_about


input_boolean:
  # Icons from https://materialdesignicons.com/
  car_alarm_triggered:
    name: Car Alarm Triggered
    icon: mdi:shield-car
  house_alarm_triggered:
    name: House Alarm Triggered
    icon: mdi:shield-home
  ignore_time_of_day:
    name: Ignore time of day, light/dark
    icon: mdi:timer-off
  immediate_closet_off:
    name: Immediately respond to closet closing to turn lights off
    icon: mdi:lightbulb-auto
  pending_mercedes_start:
    name: Flag Mercedes to start
    initial: false
    icon: mdi:car-cog
  pending_narvans_ladder_action_reset:
    name: Flag Narvan's ladder reset
    initial: false
    icon: mdi:ladder
  pending_relinquish_to_motion:
    name: Flag relinquish to motion
    initial: false
    icon: mdi:motion-sensor
  pending_occupancy_mode_solo:
    name: Flag occupancy mode to solo
    icon: mdi:account
  pending_occupancy_mode_guests_compatible:
    name: Flag occupancy mode to guests (compatible)
    icon: mdi:account-group
  pending_occupancy_mode_guests_deviant:
    name: Flag occupancy mode to guests (deviant)
    icon: mdi:deviantart
  pending_occupancy_mode_party:
    name: Flag occupancy mode to party
    icon: mdi:party-popper
  pending_power_select_tvpc_office_ir:
    name: "Flag power on and select source for TV+PC Office Inside/Right"
    initial: false
    icon: mdi:arrow-expand-right
  pending_power_select_tvpc_office_ol:
    name: "Flag power on and select source for TV+PC Office Outside/Left"
    initial: false
    icon: mdi:arrow-expand-left
  pending_power_select_tvpc_office_all:
    name: "Flag power on and select source for TV+PC Office All"
    initial: false
    icon: mdi:arrow-split-vertical
  pending_reset_alexa_volume:
    name: Flag reset of Alexa volume
    initial: false
    icon: mdi:volume-source
  pending_workout_finish:
    name: Flag workout finish
    initial: false
    icon: mdi:music-rest-whole
  pending_yamaha_airplay_input:
    name: Flag yamaha airplay input select
    initial: False
    icon: mdi:cast-audio-variant
  pending_yamaha_alexa_input:
    name: Flag yamaha alexa input select
    initial: False
    icon: mdi:cast-audio
  pending_yamaha_nvidia_shield_input:
    name: Flag yamaha NVidia Shield input select
    initial: False
    icon: mdi:album
  pending_yamaha_vinyl_input:
    name: Flag yamaha vinyl input select
    initial: False
    icon: mdi:album
  pending_yamaha_skip_next:
    name: Flag skip next on yamaha
    initial: false
    icon: mdi:skip-next
  request_alexa_wheres_the_beer:
    name: Request where's the beer from Alexa
    initial: false
    icon: mdi:glass-mug-variant
  spotlight_mode:
    name: Spotlight mode (single occ)
    icon: mdi:spotlight
  stealth_mode:
    name: Stealth mode
    icon: mdi:incognito-circle
  use_digoo_over_aqara:
    name: Use Digoo isntead of Aqara
    icon: mdi:test-tube


input_select:
  alarm_alert:
    name: Alarm Alert Status
    options:
      - Cleared
      - Alert active
      - Acknowledged
    icon: mdi:shield
  narvans_ladder_action:
    name: "Narvan's black step ladder (queued action)"
    options:
      - None
      - Advance
      - Reset
    icon: mdi:ladder
  occupancy_mode:
    name: Occupancy Mode
    options:
      - Solo
      - Guests (compatible)
      - Guests (deviant)
      - Party
    icon: mdi:account-box-multiple


input_text:
  alexa_actionable_notification:
    name: Alexa Actionable Notification Holder
    max: 255
    initial: '{"text":
        "This is a test of the alexa actions custom skill. Did it work?",
        "event": "actionable.skill.test"}'
  narvans_ladder_next_response:
    name: "Narvan's black step ladder (next response)"
    max: 255
    initial: "I'm not sure"


intent_script:
  NarvansLadderIntent:
    action:
      service: input_select.select_option
      data:
        option: Advance
      target:
        entity_id: input_select.narvans_ladder_action
    async_action: true
    speech:
      type: plain
      text: "{{ states('input_text.narvans_ladder_next_response') }}"
  SetVolumeIntent:
    action:
      service: media_player.volume_set
      target:
        entity_id: media_player.yamaha_receiver
      data:
        volume_level: "{{ [[0.2, 1 - (volume_db | float | abs) / 100] | max, 1] | min }}"
    speech:
      type: plain
      text: Yamaha set to {{ -1 * ([[0, volume_db | float | abs] | max, 80] | min) }} db


light: !include lights.yaml

logbook:


logger:
  default: warning
  # logs:
    # custom_components.mbapi2020: debug
    # homeassistant.components.alexa: debug
    #homeassistant.components.python_script: debug


lovelace:
  mode: yaml
  dashboards:
    lovelace-by-location:
      mode: yaml
      filename: ui-by-location.yaml
      title: By Location
      icon: mdi:map-marker-multiple
    lovelace-by-group-location:
      mode: yaml
      filename: ui-by-group-location.yaml
      title: By Group Location
      icon: mdi:map-marker-radius
    lovelace-by-type:
      mode: yaml
      filename: ui-by-type.yaml
      title: By Type
      icon: mdi:billiards-rack
  resources:
    - url: /local/zigbee2mqtt-networkmap.js?v=0.7.0
      type: module


media_player:
  - platform: yamaha
    host: 192.168.1.64
    source_ignore:
      - "AUDIO1"
      - "AUDIO2"
      - "AV1"
      - "AV2"
      - "AV3"
      - "AV4"
      - "AV5"
      - "Deezer"
      - "HDMI3"
      - "HDMI4"
      - "HDMI5"
      - "SiriusXM"
      - "USB"
      - "V-AUX"
    source_names:
      HDMI1: "Nvidia Shield"
      HDMI2: "Xbox 360"
      PHONO: "Turntable / Vinyl"
      AV6: "Alexa Echo"

mobile_app:

mqtt: !include mqtt.yaml

python_script:
recorder:


rest_command:
  autoremote_mercedes_start:
    url: !secret autoremote_msg_mercedes_start


script: !include_dir_merge_named scripts


switch:
  - platform: wake_on_lan
    mac: 8c:dc:d4:29:71:74
    host: 192.168.1.79
    name: Office IR TVPC
    turn_off:
      service: mqtt.publish
      data:
        topic: "iotlink/workgroup/tvpc-office-ir/commands/suspend"

  - platform: wake_on_lan
    mac: 64:51:06:5e:c7:e6
    host: 192.168.1.75
    name: Office OL TVPC
    turn_off:
      service: mqtt.publish
      data:
        topic: "iotlink/workgroup/tvpc-office-ol/commands/suspend"


system_health:
sun:
# variable:
wake_on_lan:
webhook:
