
- platform: template
  sensors:
      last_alexa:
        entity_id:
          - media_player.alexa_apps_jc
          - media_player.alexa_dining_room
          - media_player.alexa_living_room
          - media_player.alexa_master_bedroom
          - media_player.alexa_note_10_jc
          - media_player.alexa_office
        value_template: >
          {{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
