
# Digoo Remote FOBs not really a "sensor", but convenient to debounce and name

# Digoo Remote Key FOB #01
- platform: mqtt
  state_topic: rtl_433/Digoo-Security__648488
  name: Remote FOB Digoo Floater 1
  value_template: "{{ value_json.button }}"
  qos: 1
  expire_after: 1


# Digoo Remote Key FOB #02
- platform: mqtt
  state_topic: rtl_433/Digoo-Security__380008
  name: Remote FOB Digoo Floater 2
  value_template: "{{ value_json.button }}"
  qos: 1
  expire_after: 1


- platform: template
  sensors:
      last_alexa:
        entity_id:
          - media_player.alexa_apps_jc
          - media_player.alexa_dining_room
          - media_Player.alexa_downstairs_bathroom
          - media_Player.alexa_kitchen
          - media_Player.alexa_laundry_room
          - media_player.alexa_living_room
          - media_player.alexa_master_bedroom
          - media_Player.alexa_music_room
          - media_player.alexa_note_10_jc
          - media_Player.alexa_office
          - media_Player.alexa_upstairs_bathroom
        value_template: >
          {{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
