
- platform: template
  sensors:
      last_alexa:
        entity_id:
          - media_player.this_device
          - media_player.jonathan_s_alexa_apps
          - media_player.jonathan_s_dining_room_echo_dot
          - media_player.jonathan_s_living_room_echo_dot
          - media_player.jonathan_s_master_bedroom_echo_dot
        value_template: >
          {{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
