# https://www.zigbee2mqtt.io/information/configuration.html

# Required: allow new devices to join.
# WARNING: Disable this after all devices have been paired! (default: false)
permit_join: false

devices:
  - devices_new.yaml

# Required: Home Assistant integration (MQTT discovery) (default: false)
homeassistant: true

# Required: MQTT settings
mqtt:
  # Required: MQTT base topic for Zigbee2MQTT MQTT messages
  base_topic: zigbee2mqtt

  # Required: MQTT server URL (use mqtts:// for SSL/TLS connection)
  server: 'mqtt://localhost'

  # MQTT server authentication, uncomment if required:
  user: zigbee2mqtt
  password: password1


# Required: serial settings
serial:
  # Required: location of the adapter (e.g. CC2531).
  # To autodetect the port, set 'port: null'.
  port: /dev/ttyACM0


advanced:
  # Optional: Home Assistant discovery topic (default: shown below)
  homeassistant_discovery_topic: 'homeassistant'
  # Optional: Home Assistant status topic (default: shown below)
  homeassistant_status_topic: 'homeassistant/status'
  # Optional: Home Assistant legacy triggers (default: shown below), when enabled:
  # - Zigbee2mqt will send an empty 'action' or 'click' after one has been send
  # - A 'sensor_action' and 'sensor_click' will be discoverd
  homeassistant_legacy_triggers: false
