devices:
  - devices_buttons.yaml
  - devices_doorwins.yaml
  - devices_motion.yaml
  - devices_outlets.yaml
  - devices_water.yaml
homeassistant:
  enabled: true
  status_topic: homeassistant/status
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://localhost
  user: '!secret user'
  password: '!secret password'
serial:
  port: /dev/ttyACM0
  adapter: zstack
advanced:
  channel: 25
  network_key: '!secret network_key'
device_options: {}
version: 4
